name: Maven Package

on:
  release:
    types: [created]
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: List workspace contents
      run:  Get-ChildItem -Path $env:GITHUB_WORKSPACE
    # Conditionally publish to GitHub Packages only for release events
    - name: Publish to GitHub Packages Apache Maven
      if: github.event_name == 'release'
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
